### ISSUE TITLE
Negative energy consumption allowed

### ISSUE THREAD

**Issue by maxine-red** [tomdodd4598/NuclearCraft#690]
I'm not sure if this is a bug or feature, as I would like it to work as a feature.

Anyway, thing is that you can set negative energy consumption values and a machine is producing energy.

I actually wanted to use this to make a workaround for the missing heat exchanger (put hot coolant into supercooler and get cold coolant + energy out).

It works that it fills up with energy, but I can't get the energy out of that machine. (Which is why I assume it's a bug).

I do like it to become a feature though, so you can then have cool setups, like the one I tried to accomplish.

Versions
NC: 2o.4.0-1.12.2
Forge: 14.23.5.2847

I tested pulling energy with thermal fluxducts and also with immersive engineering power lines.
Also only tested it with negative numbers in the config file for base power. I haven't tried crafttweaker recipes with negative power , as of now. But I am going to try that soon-ish.

It won't effect normal gameplay, but allow modpack makers more freedom.

**Comment by turbodiesel4598** [comment]
This has been requested before - it's a bit tricky with the way machines are currently implemented, but at some point they may get a refactor and allow for stuff like this :)

**Comment by tomdodd4598** [comment]
Sorry for the very late reply, but this should be implemented in the next version of NCO for any custom machines which are defined as generators :)

Additionally, since your original comment, igentuman has actually added a whole bunch of machines to fill in for the currently missing heat exchanger mechanics, as well as having some other auxiliary uses, in his addon called [Steam Additions](https://www.curseforge.com/minecraft/mc-mods/nc-steam-additions).
